Repository bcgov/platform-services-registry, pull requests merged in 2021-01, with the labels that each got.

#259 The status message should let teams know what is pending
  web/src/components/ProfileEditableQuota.tsx
  web/src/views/ProfileEditable.tsx
Labels: bug

#250 Contact Edit Feature
  api/__tests__/__snapshots__/contact.spec.ts.snap
  api/__tests__/contact.spec.ts
  api/__tests__/fixtures/provisioning-context.json
  api/__tests__/fixtures/select-contact-edit-request.json
  api/doc/api.yaml
  api/public/doc/api/index.html
  api/src/controllers/contact.ts
  api/src/controllers/profile.ts
  api/src/controllers/provision.ts
  api/src/db/model/request.ts
  api/src/libs/fulfillment.ts
  api/src/libs/utils.ts
  api/src/router/routes/profile.ts
  web/README.md
  web/src/__tests__/transformDataHelper.test.tsx
  web/src/components/ProfileEditableContact.tsx
  web/src/utils/transformDataHelper.tsx
  web/src/utils/useRegistryApi.tsx
  web/src/views/ProfileEditable.tsx
Labels: component/api, component/web

#267 Refactor pendingEditRequest
  web/src/utils/getProfileStatus.tsx
  web/src/views/ProfileEditable.tsx
Labels: component/web

#283 Hotfix/migration note
  web/src/__tests__/__snapshots__/ProfileCreate.test.tsx.snap
  web/src/components/common/UI/FormSubtitle.tsx
  web/src/components/profileCreate/CreateFormProject.tsx
Labels: hotfix

#284 Update description of migration status note
  web/src/__tests__/__snapshots__/ProfileCreate.test.tsx.snap
  web/src/components/profileCreate/CreateFormProject.tsx
Labels: hotfix

#271 Edit project description
  api/__tests__/__snapshots__/contact.spec.ts.snap
  api/__tests__/__snapshots__/profile.spec.ts.snap
  api/__tests__/fixtures/provisioning-context.json
  api/__tests__/profile.spec.ts
  api/doc/api.yaml
  api/public/doc/api/index.html
  api/src/controllers/profile.ts
  api/src/controllers/provision.ts
  api/src/db/model/request.ts
  api/src/libs/fulfillment.ts
  api/src/router/routes/profile.ts
  web/src/components/profileEdit/ProjectCardEdit.tsx
  web/src/hooks/useRegistryApi.tsx
  web/src/views/ProfileEdit.tsx
Labels: component/api, component/web

#292 Fix frontend routes so logout is working without throwing errors
  web/src/AppRouter.tsx
  web/src/utils/AppRoute.tsx
  web/src/utils/PrivateRoute.tsx
Labels: bug
